config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'statics#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :statics, only: [:new]
  resources :posts,  except: [:destroy]
  resources :users,  except: [:destroy, :index]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { in: 3..30 }
  validates :content, presence: true, length: { in: 20..500 }

  def author
    User.find_by(id: user_id).name
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :posts
  before_create :remember

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d]+\.[a-z]+\z/i.freeze

  validates :name, presence: true

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.digest(string)
    BCrypt::Password.create(string)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    self.remember_digest = User.digest(@remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include SessionsHelper
  include PostsHelper

  before_action :post_logged_in?, only: %i[new create edit update]
  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'Post Created'
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit; end

  private

  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end

  def post_logged_in?
    return if logged_in?

    flash[:danger] = 'Log in first'
    redirect_to login_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out(current_user) if logged_in?
    redirect_to root_path
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def new; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Sign up successfull'
      log_in(@user)
      redirect_to @user
    else
      flash.now[:warnign] = 'Sign up unsuccessfull'
      render 'new'
    end
  end

  def edit; end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def current_post
    @current_post = Post.find_by(id: params[:id])
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    cookies.signed[:user_id] = user.id
    cookies[:remember_token] = user.remember_token
  end

  def current_user
    return unless (user_id = cookies.signed[:user_id])

    @current_user ||= User.find_by(id: user_id)
    log_in(@current_user) if @current_user
    @current_user
  end

  def current_user=(user)
    @current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <%if logged_in?%>
      <div>
        <%= link_to "Log out", logout_path, method: :delete %>
         <%= link_to "Create post", new_post_path%>
      </div>
    <%else%>
      <div>
        <%= link_to "Log in", login_path %>
        <%= link_to "Sign up", new_user_path %>
      </div>
    <% end %>
    <%= link_to "Home", root_path %>
    <h1><%= link_to "Posts Index", posts_path %></h1>

  <nav>
    <% flash.each do |message_type, message| %>
      <div class="<%= message_type %>"><%= message %></div>
    <% end %>
    
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/posts/_post.html.erb
<li>
  <%= link_to post.title, post%>
  <%if logged_in?%>
      <div>
        <p>Author: <%= User.find_by(id: post.user_id).name%></p>
      </div>
    <% end %>
</li>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<ul>
    <%= render @posts %>
</ul>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

<%=form_for @post do |f|%>
    <%=render 'shared/posts_error_messages' %>
    <%=f.label :title, 'Post Title'%>
    <%=f.text_field :title%>
    <%=f.label :content, 'Story:'%>
    <%=f.text_area :content%>
    <%=f.hidden_field :user_id, value: current_user.id%>

    <%=f.submit "Create Post"%>    

<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

<%if logged_in?%>
    <div>
    <p>Post Author: <%=current_post.author%></p>
    </div>
<% end %>


<div>
    <h1><%=current_post.title%></h1>
    <div>
        <p><%=current_post.content%></p>
    <div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_posts_error_messages.html.erb
<% if @post.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize(@post.errors.count, "error") %>.
    </div>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_users_error_messages.html.erb
<% if @user.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    asdasd
    <%=@user.errors%>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/statics/new.html.erb
<h1>Statics#new</h1>
<p>Find me in app/views/statics/new.html.erb</p>

<%if logged_in?%>
    <div>
    <%= link_to "Log out", logout_path %>
    <%= link_to "Create post", new_post_path%>
    </div>
<%else%>
    <div>
    <%= link_to "Log in", login_path %>
    <%= link_to "Sign up now!", new_user_path%>
    </div>
<% end %>

<%= link_to "Read posts", posts_path%>

app/views/users/edit.html.erb
<h1>Users#edit,</h1>
<p>Find me in app/views/users/edit,.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
    
    

<%=form_with model: @user, local: true do |f|%>
    <div>
    <%=render 'shared/users_error_messages'%>
    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    </div>
    <%=f.label :name, "Username"%>
    <%=f.text_field :name%>
    <%=f.label :email%>
    <%=f.email_field :email%>
    <%=f.label :password%>
    <%=f.password_field :password%>
    <%=f.label :password_confirmation%>
    <%=f.password_field :password_confirmation%>
    <%=f.submit "Create account"%>    

<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%=@user.name%>